import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/NavBar";
import { Raleway } from "next/font/google";
import Footer from "@/components/Footer";

const raleway = Raleway({
  subsets: ["latin"], 
  weight: ["400", "500", "700"], 
});


export const metadata: Metadata = {
  title: "Movies",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={raleway.className}
      >

        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
